SocialNetwork/WebApplication/Controllers/MessagesController.cs
using BusinessLogic;
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    [Authorize]
    public class MessagesController : Controller
    {
        private DataManager dataManager;
        public MessagesController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }
        

        public ActionResult Index()
        {
            //Готовим входящие сообщения и авторов и передаем их в ViewModel а далее в представление
            List<IncomingMessageViewModel> model = new List<IncomingMessageViewModel>();
            foreach (IncomingMessage message  in dataManager.Messages.GetIncomingMessagesByUserId((int)Membership.GetUser().ProviderUserKey))
            {
                model.Add(new IncomingMessageViewModel
                {
                    Message = message,
                    UserForm = dataManager.Users.GetUserById(message.UserFromId)
                });
            }
            return View(model);
        }

        public ActionResult Outgoing ()
        {
            //Подготавливаем исходящие сообщения и адресатов
            List<OutgoingMessageViewModel> model = new List<OutgoingMessageViewModel>();
            foreach(OutgoingMessage message in dataManager.Messages.GetOutgoingMessagesByUserId((int)Membership.GetUser().ProviderUserKey))
            {
                model.Add(new OutgoingMessageViewModel
                {
                    Message = message,
                    UserTo = dataManager.Users.GetUserById(message.UserToId)
                });
            }
                return View(model);
        }

        public ActionResult NewMessage(int userToId)
        {
            //Определяем автора сообщения,адресата и дату создания

            return View(new OutgoingMessage
                        { UserId= (int)Membership.GetUser().ProviderUserKey,
                        UserToId =userToId,
                        CreatedDate =DateTime.Now});
        }

        [HttpPost]
        public ActionResult NewMessage(OutgoingMessage message)
        {
            if(ModelState.IsValid)
            {
                dataManager.Messages.SaveOutgoingMessage(message);
                dataManager.Messages.SaveIncomingMessage(new IncomingMessage
                                                                    {
                                                                        UserId = message.UserToId,
                                                                        UserFromId = message.UserId,
                                                                        CreatedDate = DateTime.Now,
                                                                        Text = message.Text

                                                                    });
                return RedirectToAction("Index", "Home");
            }
            return View(message);
        }
    }
}

SocialNetwork/WebApplication/Views/Messages/Index.cshtml
@using WebApplication.Models
@model List<IncomingMessageViewModel>

@{
    ViewBag.Title = "Мои сообщения";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Входящие | @Html.ActionLink("Исходящие", "Outgoing", "Messages") </h2>
<table>
    <tr>
        <td style="padding-right:10px; font-size:14px;">От кого</td>
        <td>Когда</td>
        <td> </td>
    </tr>

    @foreach (IncomingMessageViewModel message in Model)
    {
    <tr>
        <td style="padding-right:10px; font-size:14px;">@message.UserForm.LastName @message.UserForm.FirstName </td> 
        <td style="padding-right:10px; font-size:14px;">@message.Message.CreatedDate.ToShortDateString()</td>
        <td>@message.Message.Text </td>
    </tr>
    }
</table>

SocialNetwork/WebApplication/Views/Messages/NewMessage.cshtml
@using Domain.Entities
@model OutgoingMessage
@{
    ViewBag.Title = "Новое сообщение";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Новое сообщение</h2>
@using (Html.BeginForm())
{
    @Html.HiddenFor(x => x.UserId)
    @Html.HiddenFor(x => x.UserToId)
    @Html.HiddenFor(x => x.CreatedDate)

    <p>
        Введите текст сообщения: <br />
        @Html.TextAreaFor(x => x.Text)
        @Html.ValidationMessageFor(x => x.Text)
    </p>
   <input type="submit" value="Отправить" />
}

SocialNetwork/WebApplication/Views/Messages/Outgoing.cshtml
@using WebApplication.Models
@model List<OutgoingMessageViewModel>
@{
    ViewBag.Title = "Мои сообщения";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Html.ActionLink("Входящие", "Index", "Messages") | Исходящие </h2>
<table>
    
    <tr >
        
        <td style="padding-right:10px; font-size:14px;">Кому</td> &nbsp;
        <td>Когда</td> &nbsp;
        <td rowspan="2"></td>
    </tr>
  
    @foreach (OutgoingMessageViewModel message in Model)
    {
        <tr>

            <td  style="padding-right:10px; font-size:14px;">@message.UserTo.LastName @message.UserTo.FirstName </td> &nbsp;
            <td  style="padding-right:10px; font-size:14px;">@message.Message.CreatedDate.ToShortDateString()</td> &nbsp;
            <td  style="color: #333366; font-size:16px;" rowspan="2" ; width: 160px;  word-break: break-all;>@message.Message.Text </td>
        </tr>
    }
</table>